---
title: "Physical activity analysis"
output: html_document
---

## Libraries
```{r}
library(caret)

```
## Import data sets
```{r}
training<-read.csv("pml-training.csv",na.strings=c("NA","#DIV/0!"))
testing<-read.csv("pml-testing.csv",na.strings=c("NA","#DIV/0!"))
```
## Researching data
```{r}
dim(training)
table(training$classe)
```
## Removing NA
```{r}
NA_Count = sapply(1:dim(training)[2],function(x)sum(is.na(training[,x])))
NA_list = which(NA_Count>0)
colnames(training[,c(1:7)])
training = training[,-NA_list]
training = training[,-c(1:7)]
training$classe = factor(training$classe)
testing = testing[,-NA_list]
testing = testing[,-c(1:7)]
```
## Modeling
```{r}
set.seed(8888)
cv3 = trainControl(method="cv",number=3,allowParallel=TRUE,verboseIter=TRUE)
modrf = train(classe~., data=training, method="rf",trControl=cv3)
modtree = train(classe~.,data=training,method="rpart",trControl=cv3)
prf=predict(modrf,training)
ptree=predict(modtree,training)
table(prf,training$classe)
table(ptree,training$classe)
prf=predict(modrf,testing)
ptree=predict(modtree,testing)
table(prf,ptree)
```
## Answers
```{r}
answers=predict(modrf,testing)
answers
```